-- Ferramentaria NET PR — schema completo para NOVO projeto Supabase
-- Rode isto UMA VEZ no SQL Editor do projeto novo (Production).

-- ========== USUÁRIOS (login no app) ==========
create table if not exists public.usuarios (
  id text primary key,
  nome text not null,
  usuario text not null unique,
  senha text not null,
  cargo text not null,
  ccs jsonb not null default '[]'::jsonb,
  permissions jsonb not null default '{}'::jsonb,
  ativo boolean not null default true,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_usuarios_usuario on public.usuarios (usuario);

-- ========== ITENS ==========
create table if not exists public.itens (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nome text not null,
  valor numeric not null default 0,
  qtd_kit_mdu numeric not null default 0,
  qtd_kit_inst numeric not null default 0,
  minimos jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_itens_codigo on public.itens (codigo);

-- ========== TÉCNICOS ==========
create table if not exists public.tecnicos (
  id bigint generated by default as identity primary key,
  nome text not null,
  cc text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_tecnicos_cc on public.tecnicos (cc);

-- ========== MOVIMENTAÇÕES ==========
create table if not exists public.movimentacoes (
  id bigint generated by default as identity primary key,
  tipo text not null,
  item_id bigint,
  tecnico_id bigint,
  cc text,
  quantidade numeric not null default 0,
  observacao text,
  created_at timestamptz not null default now()
);
create index if not exists idx_movimentacoes_created_at on public.movimentacoes (created_at desc);
create index if not exists idx_movimentacoes_cc on public.movimentacoes (cc);

-- ========== TRIANGULAÇÕES (solicitações entre CCs) ==========
create table if not exists public.triangulacoes (
  id text primary key,
  cc_origem text not null,
  cc_destino text not null,
  item_id bigint not null,
  quantidade numeric not null default 0,
  observacao text,
  solicitado_por text,
  solicitado_nome text,
  status text not null default 'Pendente',
  aprovado_por text,
  aprovado_nome text,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_triangulacoes_created_at on public.triangulacoes (created_at desc);
create index if not exists idx_triangulacoes_status on public.triangulacoes (status);

-- ========== Acesso rápido (app usa anon key no front) ==========
-- Em produção depois você pode reativar RLS com políticas específicas.
alter table public.usuarios disable row level security;
alter table public.itens disable row level security;
alter table public.tecnicos disable row level security;
alter table public.movimentacoes disable row level security;
alter table public.triangulacoes disable row level security;

-- ========== Admin inicial (ajuste a senha depois no app) ==========
insert into public.usuarios
(id, nome, usuario, senha, cargo, ccs, permissions, ativo, must_change_password)
values
(
  'admin-seed',
  'Administrador',
  'admin',
  'admin123',
  'Admin',
  '["CC NET APOIO PR","CC NET CTA PR","CC NET LDA PR","CC NET MGA PR","CC NET LITORAL PR","CC NET SUDOESTE PR"]'::jsonb,
  '{"triangulacaoAcesso":true,"triangulacaoSolicitar":true,"triangulacaoAprovar":true,"visualizarValores":true,"cadastroItens":true,"cadastroTecnicos":true}'::jsonb,
  true,
  false
)
on conflict (usuario) do nothing;
